# Uncomment the following lines when deployed on RPi
#logging:
#    file: /home/maja/log/airmes.log
#    level:
#        com.maja.airmes: INFO

spring:
    main:
        banner-mode: log
    application:
        name: Airmes